import type { CapabilityRecord } from "./types.js";

export const WORKBENCH_CAPABILITIES: readonly CapabilityRecord[] = [
  { id: "capability:sketch-entities", workspace: "sketch", name: "Line, rectangle, circle, arc", level: "preview", summary: "Bounded XY entities with snapping and stable IDs." },
  { id: "capability:sketch-constraints", workspace: "sketch", name: "Constraint diagnostics", level: "preview", summary: "Supported constraint records and explainable DOF estimate." },
  { id: "capability:sketch-dimensions", workspace: "sketch", name: "Driving sketch dimensions", level: "preview", summary: "Atomic bounded line-length, rectangle-width/height, and circle-radius edits with visible dimension records." },
  { id: "capability:bracket-solid", workspace: "part", name: "Centered-bore solid", level: "qualified", summary: "Worker-validated closed manifold mesh-solid in the published envelope." },
  { id: "capability:part-depth", workspace: "part", name: "Bounded analytic features", level: "preview", summary: "Closed-mesh revolve, pattern, mirror, aligned unite, through-cylinder subtract, trim, blend, chamfer, draft, shell, and planar face edits with revisioned precondition diagnostics." },
  { id: "capability:viewport-navigation", workspace: "part", name: "CAD viewport navigation", level: "preview", summary: "Orbit, pan, wheel zoom, fit, named views, perspective/orthographic projection, view box, grid, and axis triad." },
  { id: "capability:viewport-measure", workspace: "part", name: "Point-to-point measurement", level: "preview", summary: "Two triangle-ray picks report point coordinates, XYZ deltas, and Euclidean distance." },
  { id: "capability:exchange-import", workspace: "part", name: "Local 3D reference import", level: "preview", summary: "GLB/glTF, OBJ, STL, PLY, 3MF, COLLADA, FBX, AMF, 3DS, VRML, VTK, USD family, G-code, and XYZ with bounded local companion resolution." },
  { id: "capability:exchange-export", workspace: "part", name: "Runtime scene export", level: "preview", summary: "Visible tessellated geometry exports to GLB, glTF, OBJ, STL, PLY, and USDZ with explicit unit handling." },
  { id: "capability:pdf-model-package", workspace: "part", name: "PDF model package", level: "preview", summary: "Runtime-generated PDF page with a captured viewport image, model metrics, and an embedded GLB attachment; the committed sample verifies structure only." },
  { id: "capability:pdf-3d-pass-through", workspace: "part", name: "Interactive 3D PDF pass-through", level: "preview", summary: "Already encoded U3D or PRC bytes can be embedded as a PDF 3D annotation without re-encoding." },
  { id: "capability:assembly", workspace: "assembly", name: "Component assembly", level: "preview", summary: "Editable box/cylinder instances, visibility, position, grounding, deletion, direct mates, exploded state, and conservative AABB checks." },
  { id: "capability:container-templates", workspace: "assembly", name: "Cargo container planning templates", level: "preview", summary: "Original editable 20 ft and 40 ft high-cube planning frames seeded from nominal external envelopes; not certified structural container models." },
  { id: "capability:bess-layout", workspace: "assembly", name: "BESS container arrangement", level: "preview", summary: "Non-certified 20 ft high-cube equipment, aisle, HVAC, cable tray, PCS, switchgear, rack, and safety-system placeholder layout." },
  { id: "capability:surface", workspace: "surface", name: "Bézier and loft surfaces", level: "preview", summary: "Deterministic tessellated patches with bounded metrics." },
  { id: "capability:drawing", workspace: "drawing", name: "Associative engineering vector sheet", level: "preview", summary: "Descriptive front base view, aligned first/third-angle projections, full section A-A, reference isometric, centerlines, sheet zones, revision table, notes, and title block." },
  { id: "capability:drawing-tolerance", workspace: "drawing", name: "General tolerance annotations", level: "preview", summary: "Bounded user-defined linear and angular general tolerances with explicit unless-otherwise-specified scope." },
  { id: "capability:drawing-gdt", workspace: "drawing", name: "Explicit basic GD&T drafting", level: "preview", summary: "User-selected datum frame plus independently entered position, flatness, and perpendicularity values; general tolerance never creates or calculates GD&T." },
  { id: "capability:electrical-schematic", workspace: "electrical", name: "Electrical schematic editor", level: "preview", summary: "Original vector symbols, editable device library, stable references, explicit terminals, named AC/DC/control/ground nets, and deterministic SVG sheets." },
  { id: "capability:electrical-templates", workspace: "electrical", name: "Automatic circuit templates", level: "preview", summary: "BESS single-line, DC auxiliary, and direct-on-line motor starter concepts with connected netlists and user-defined ratings." },
  { id: "capability:electrical-erc", workspace: "electrical", name: "Electrical rule check", level: "preview", summary: "Duplicate references, broken endpoints, open terminals, protective-device presence, and ground-reference presence are checked structurally." },
{ id: "capability:electromechanical-catalog", workspace: "electrical", name: "Generic electrical-panel package catalog", level: "preview", summary: "Original MIT panel-scale generic packages cover current schematic kinds with stable IDs, mounting class, dimensions, and rotation-aware local 3D terminal coordinates." },
{ id: "capability:circuit-to-3d", workspace: "electrical", name: "Circuit-to-wired-panel realization", level: "preview", summary: "Deterministic mounting plate, DIN rails, wiring ducts, bonding hardware, generic device packages, terminal traceability, and bounded unsized orthogonal conductor visualization." },
  { id: "capability:electrical-analysis", workspace: "electrical", name: "Electrical engineering calculations", level: "unavailable", summary: "Conductor sizing, fault studies, protection coordination, arc-flash, load flow, thermal design, functional safety, and compliance require qualified project-specific methods." },
  { id: "capability:vehicle-templates", workspace: "vehicle", name: "Original vehicle skeleton templates", level: "preview", summary: "Generic ICE motorcycle, step-through scooter, EV motorcycle, delta cargo three-wheeler, and tadpole geometry-study templates with no OEM geometry or copied CAD content." },
  { id: "capability:vehicle-hardpoints", workspace: "vehicle", name: "State-dependent vehicle hardpoints", level: "preview", summary: "SI-native axle, frame, suspension, steering, powertrain, rider, and CG points with full-droop, design-ride, and full-bump preview states." },
  { id: "capability:vehicle-suspension", workspace: "vehicle", name: "Suspension spring screen", level: "preview", summary: "User-controlled travel, sag, spring rate, motion ratio, derived wheel rate, and simplified natural-frequency calculations." },
  { id: "capability:vehicle-brakes", workspace: "vehicle", name: "Brake and axle-load screen", level: "preview", summary: "Quasi-static load transfer, ideal and hardware force split, separate hydraulic circuits, equivalent-clamp-area torque, friction caps, lock margin, and stopping-distance screen." },
  { id: "capability:vehicle-stability", workspace: "vehicle", name: "Two/three-wheel stability references", level: "preview", summary: "Steady lean reference for single-track layouts and rigid triangular support-polygon load/lift screening for delta or tadpole layouts." },
  { id: "capability:vehicle-powertrain", workspace: "vehicle", name: "Powertrain and road-load operating point", level: "preview", summary: "User-entered torque/gearing, rolling and aerodynamic road loads, traction-capped force, longitudinal acceleration, and explicitly assumption-based EV energy envelope." },
  { id: "capability:vehicle-validation", workspace: "vehicle", name: "Roadworthiness and detailed vehicle validation", level: "unavailable", summary: "Structural FEA, fatigue, detailed kinematics/compliance, multibody dynamics, tire transients, thermal systems, control systems, crash, functional safety, test correlation, homologation, and fabrication release require qualified tools and engineers." },
  { id: "capability:mcp-local", workspace: "automate", name: "Local MCP stdio", level: "preview", summary: "Model-neutral modern/legacy discovery, machine-readable guide, deterministic command recipes, exact candidate preview, and receipt-gated immutable return tools." },
  { id: "capability:python-sdk", workspace: "automate", name: "Python MCP client", level: "preview", summary: "Standard-library dual-era Python client for an explicitly configured direct local MCP stdio command." },
  { id: "capability:engineering-intent", workspace: "automate", name: "Engineering intent compiler", level: "preview", summary: "Read-only decomposition of ordinary part or assembly requests into reusable definitions, ordered features, standards questions, dependency packages, approval gates, and truth-labeled execution routes." },
  { id: "capability:exact-brep", workspace: "part", name: "Exact B-rep and NURBS", level: "unavailable", summary: "Requires a separately qualified exact kernel and topology contract." },
  { id: "capability:proprietary-cad-import", workspace: "part", name: "Native proprietary CAD import", level: "unavailable", summary: "STEP/IGES exact conversion and native vendor formats require reviewed kernels, authorized SDKs, or upstream neutral export." },
  { id: "capability:remote-mcp", workspace: "automate", name: "Remote authenticated MCP", level: "preview", summary: "Deployed /api/mcp transport with OAuth or expiring bearer tokens, tenant-scoped permissions, Origin validation, a 1 MB body cap, and identity rate limiting; availability still depends on valid cloud configuration." }
];

export function capabilitiesForWorkspace(workspace: CapabilityRecord["workspace"]): readonly CapabilityRecord[] {
  return WORKBENCH_CAPABILITIES.filter((record) => record.workspace === workspace);
}
