packages:
  - "apps/*"
  - "packages/*"

catalogMode: strict

autoInstallPeers: false

ignoredOptionalDependencies:
  - "@img/sharp-*"

allowBuilds:
  esbuild: true

catalog:
  '@mediapipe/tasks-vision': 1.0.1
  esbuild-wasm: 0.28.2
